"""P2 业务七表：主数据 · 订单 · 库存 · 排产

Revision ID: 5b9c3e014e06
Revises: 354295b4edfe
Create Date: 2026-09-10 14:21:55.173999
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5b9c3e014e06"
down_revision: str | None = "354295b4edfe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "color",
        sa.Column("bu_code", sa.String(length=8), nullable=False),
        sa.Column("color_code", sa.String(length=32), nullable=False),
        sa.Column(
            "color_name",
            sa.String(length=64),
            nullable=False,
            comment="「米白」「藏青」—— 自然语言检索入口",
        ),
        sa.Column(
            "color_family",
            sa.String(length=32),
            nullable=False,
            comment="白色系/深色系/彩色系，与色差判定的例外规则挂钩",
        ),
        sa.Column(
            "is_dark",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="明度 L* < 30",
        ),
        sa.Column(
            "std_sample_ref",
            sa.String(length=64),
            nullable=True,
            comment="标准样编号；BU-C 统一为集团标准白度色板",
        ),
        sa.PrimaryKeyConstraint("bu_code", "color_code", name=op.f("pk_color")),
    )
    op.create_table(
        "inventory_batch",
        sa.Column("batch_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("warehouse_code", sa.String(length=16), nullable=False),
        sa.Column("bu_code", sa.String(length=8), nullable=False),
        sa.Column("product_code", sa.String(length=32), nullable=False),
        sa.Column(
            "batch_no",
            sa.String(length=32),
            nullable=False,
            comment="染缸号 D2601-08 / 窑批号 K2603-15",
        ),
        sa.Column("color_code", sa.String(length=32), nullable=False),
        sa.Column("grade", sa.String(length=16), nullable=False, comment="优等品/一等品/合格品"),
        sa.Column("spec", sa.String(length=64), nullable=False),
        sa.Column(
            "delta_e", sa.Numeric(precision=5, scale=2), nullable=True, comment="本批 vs 标准大样"
        ),
        sa.Column("qty_available", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column(
            "qty_locked",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("0"),
            nullable=False,
            comment="P2 恒为 0，预留",
        ),
        sa.Column("uom", sa.String(length=8), nullable=False),
        sa.Column("inbound_date", sa.Date(), nullable=True),
        sa.Column(
            "qc_status", sa.String(length=16), nullable=True, comment="待检/合格/让步接收/不合格"
        ),
        sa.CheckConstraint(
            "grade IN ('优等品', '一等品', '合格品')", name=op.f("ck_inventory_batch_grade_enum")
        ),
        sa.CheckConstraint("qty_available >= 0", name=op.f("ck_inventory_batch_qty_nonneg")),
        sa.PrimaryKeyConstraint("batch_id", name=op.f("pk_inventory_batch")),
        sa.UniqueConstraint(
            "warehouse_code",
            "product_code",
            "batch_no",
            "color_code",
            "grade",
            name="uq_inventory_batch_identity",
        ),
    )
    op.create_index(
        "ix_inventory_batch_lookup",
        "inventory_batch",
        ["bu_code", "product_code", "color_code"],
        unique=False,
    )
    op.create_table(
        "product",
        sa.Column(
            "product_code",
            sa.String(length=32),
            nullable=False,
            comment="P-A-1001 印染 / P-B-2001 瓷砖 / P-C-3001 洁具",
        ),
        sa.Column("bu_code", sa.String(length=8), nullable=False),
        sa.Column(
            "product_name",
            sa.String(length=128),
            nullable=False,
            comment="「岩板 900×1800 素色系列」—— 自然语言检索入口",
        ),
        sa.Column(
            "category",
            sa.String(length=32),
            nullable=False,
            comment="坯布/印花布 · 岩板/瓷砖 · 坐便器/面盆/浴缸",
        ),
        sa.Column("spec", sa.String(length=64), nullable=False, comment="展示用规格字符串"),
        sa.Column(
            "attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="按 BU 发散的结构化属性",
        ),
        sa.Column(
            "default_uom",
            sa.String(length=8),
            nullable=False,
            comment="米/平方米/件 —— 业务表 uom 的权威来源",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'active'"),
            nullable=False,
            comment="active / discontinued",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("product_code", name=op.f("pk_product")),
    )
    op.create_index("ix_product_attrs", "product", ["attrs"], unique=False, postgresql_using="gin")
    op.create_index("ix_product_bu_category", "product", ["bu_code", "category"], unique=False)
    op.create_index(
        "ix_product_name_trgm",
        "product",
        ["product_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"product_name": "gin_trgm_ops"},
    )
    op.create_table(
        "production_line",
        sa.Column(
            "line_code",
            sa.String(length=32),
            nullable=False,
            comment="染缸 D-01 / 窑炉 K-03 / 成型线 F-02",
        ),
        sa.Column("bu_code", sa.String(length=8), nullable=False),
        sa.Column("line_name", sa.String(length=64), nullable=False),
        sa.Column(
            "line_type",
            sa.String(length=32),
            nullable=False,
            comment="染缸/定型机 · 压机/窑炉/抛光线 · 注浆线/隧道窑",
        ),
        sa.Column("capacity_per_hour", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column(
            "capacity_uom",
            sa.String(length=8),
            nullable=False,
            comment="米/小时 · 平方米/小时 · 件/小时",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'running'"),
            nullable=False,
            comment="running / maintenance / idle",
        ),
        sa.PrimaryKeyConstraint("line_code", name=op.f("pk_production_line")),
    )
    op.create_index(
        "ix_production_line_bu_type", "production_line", ["bu_code", "line_type"], unique=False
    )
    op.create_table(
        "production_plan",
        sa.Column("plan_no", sa.String(length=32), nullable=False),
        sa.Column("bu_code", sa.String(length=8), nullable=False),
        sa.Column("line_code", sa.String(length=32), nullable=False),
        sa.Column("product_code", sa.String(length=32), nullable=False),
        sa.Column("color_code", sa.String(length=32), nullable=False),
        sa.Column(
            "process_stage",
            sa.String(length=32),
            nullable=False,
            comment="前处理/染色/后整理 或 压机/窑炉/抛光/分级",
        ),
        sa.Column("stage_seq", sa.SmallInteger(), nullable=False),
        sa.Column("planned_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column(
            "qty_completed",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("0"),
            nullable=False,
            comment="实际完成量",
        ),
        sa.Column("uom", sa.String(length=8), nullable=False),
        sa.Column("plan_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("plan_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "changeover_min",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="换色/换规格调机时长（分钟），延误推理关键",
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("related_order_line", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "status IN ('待排', '已排', '生产中', '已完成', '暂停')",
            name=op.f("ck_production_plan_status_enum"),
        ),
        sa.CheckConstraint("plan_end >= plan_start", name=op.f("ck_production_plan_plan_window")),
        sa.PrimaryKeyConstraint("plan_no", name=op.f("pk_production_plan")),
    )
    op.create_index(
        "ix_production_plan_line_queue", "production_plan", ["line_code", "plan_end"], unique=False
    )
    op.create_index(
        "ix_production_plan_order_line", "production_plan", ["related_order_line"], unique=False
    )
    op.create_table(
        "sales_order",
        sa.Column("order_no", sa.String(length=32), nullable=False, comment="SO-2026-000123"),
        sa.Column("bu_code", sa.String(length=8), nullable=False),
        sa.Column("customer_code", sa.String(length=32), nullable=False, comment="化名客户编码"),
        sa.Column(
            "customer_name",
            sa.String(length=64),
            nullable=False,
            comment="化名，如「华东建材-A001」",
        ),
        sa.Column(
            "order_type", sa.String(length=16), nullable=False, comment="经销/工程/出口/样品"
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("required_date", sa.Date(), nullable=False, comment="客户要求交期"),
        sa.Column("promised_date", sa.Date(), nullable=True, comment="承诺交期"),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("policy_code", sa.String(length=32), nullable=True, comment="适用营销政策"),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirm_token", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "status IN ('待评审', '已确认', '生产中', '部分发货', '已完成', '已取消')",
            name=op.f("ck_sales_order_status_enum"),
        ),
        sa.PrimaryKeyConstraint("order_no", name=op.f("pk_sales_order")),
        sa.UniqueConstraint("confirm_token", name="uq_sales_order_confirm_token"),
    )
    op.create_index("ix_sales_order_bu_status", "sales_order", ["bu_code", "status"], unique=False)
    op.create_index("ix_sales_order_required_date", "sales_order", ["required_date"], unique=False)
    op.create_table(
        "sales_order_line",
        sa.Column("line_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False, comment="行号，订单内从 1 递增"),
        sa.Column("product_code", sa.String(length=32), nullable=False),
        sa.Column("spec", sa.String(length=64), nullable=False, comment="门幅×克重 / 边长×厚度"),
        sa.Column("color_code", sa.String(length=32), nullable=False),
        sa.Column(
            "grade_required", sa.String(length=16), nullable=False, comment="优等品/一等品/合格品"
        ),
        sa.Column(
            "batch_policy", sa.String(length=24), server_default=sa.text("'ANY'"), nullable=False
        ),
        sa.Column("delta_e_tolerance", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("uom", sa.String(length=8), nullable=False, comment="米 / 平方米 / 件"),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("line_status", sa.String(length=16), nullable=True),
        sa.CheckConstraint(
            "(batch_policy = 'CROSS_OK_WITHIN_TOL') = (delta_e_tolerance IS NOT NULL)",
            name=op.f("ck_sales_order_line_tolerance_iff_cross"),
        ),
        sa.CheckConstraint(
            "batch_policy IN ('SAME_BATCH', 'CROSS_OK_WITHIN_TOL', 'ANY')",
            name=op.f("ck_sales_order_line_batch_policy_enum"),
        ),
        sa.PrimaryKeyConstraint("line_id", name=op.f("pk_sales_order_line")),
        sa.UniqueConstraint("order_no", "line_no", name="uq_sales_order_line_no"),
    )
    op.create_index("ix_sales_order_line_order", "sales_order_line", ["order_no"], unique=False)
    op.create_index(
        "ix_sales_order_line_product", "sales_order_line", ["product_code"], unique=False
    )
    op.alter_column(
        "audit_log",
        "request_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="本期不采集（2026-09-09 决策）；采集前须先有脱敏",
        existing_comment="已脱敏",
        existing_nullable=True,
    )
    op.alter_column(
        "write_intent",
        "confirm_token",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="服务端铸造；客户端持有，令牌绝不进入模型上下文（§4.2）",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "session_id",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="铸造时绑定的会话；确认时须与当前 session_id 匹配（防会话劫持）",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "user_id",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="发起写操作的用户，取自 RequestContext",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "trace_id",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="铸造时的 trace_id，与 audit_log 同 trace_id 串联",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "state",
        existing_type=sa.VARCHAR(length=16),
        comment=None,
        existing_comment="pending | confirmed | cancelled | expired",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "write_intent",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="铸造时写入 now()+TTL；过期后 pending→expired",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "consumed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="confirmed 或 cancelled 的时间戳；pending 时为 NULL",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "write_intent",
        "consumed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="confirmed 或 cancelled 的时间戳；pending 时为 NULL",
        existing_nullable=True,
    )
    op.alter_column(
        "write_intent",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="铸造时写入 now()+TTL；过期后 pending→expired",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "state",
        existing_type=sa.VARCHAR(length=16),
        comment="pending | confirmed | cancelled | expired",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "write_intent",
        "trace_id",
        existing_type=sa.VARCHAR(length=64),
        comment="铸造时的 trace_id，与 audit_log 同 trace_id 串联",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "user_id",
        existing_type=sa.VARCHAR(length=32),
        comment="发起写操作的用户，取自 RequestContext",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "session_id",
        existing_type=sa.VARCHAR(length=64),
        comment="铸造时绑定的会话；确认时须与当前 session_id 匹配（防会话劫持）",
        existing_nullable=False,
    )
    op.alter_column(
        "write_intent",
        "confirm_token",
        existing_type=sa.VARCHAR(length=64),
        comment="服务端铸造；客户端持有，令牌绝不进入模型上下文（§4.2）",
        existing_nullable=False,
    )
    op.alter_column(
        "audit_log",
        "request_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="已脱敏",
        existing_comment="本期不采集（2026-09-09 决策）；采集前须先有脱敏",
        existing_nullable=True,
    )
    op.drop_index("ix_sales_order_line_product", table_name="sales_order_line")
    op.drop_index("ix_sales_order_line_order", table_name="sales_order_line")
    op.drop_table("sales_order_line")
    op.drop_index("ix_sales_order_required_date", table_name="sales_order")
    op.drop_index("ix_sales_order_bu_status", table_name="sales_order")
    op.drop_table("sales_order")
    op.drop_index("ix_production_plan_order_line", table_name="production_plan")
    op.drop_index("ix_production_plan_line_queue", table_name="production_plan")
    op.drop_table("production_plan")
    op.drop_index("ix_production_line_bu_type", table_name="production_line")
    op.drop_table("production_line")
    op.drop_index(
        "ix_product_name_trgm",
        table_name="product",
        postgresql_using="gin",
        postgresql_ops={"product_name": "gin_trgm_ops"},
    )
    op.drop_index("ix_product_bu_category", table_name="product")
    op.drop_index("ix_product_attrs", table_name="product", postgresql_using="gin")
    op.drop_table("product")
    op.drop_index("ix_inventory_batch_lookup", table_name="inventory_batch")
    op.drop_table("inventory_batch")
    op.drop_table("color")
    # ### end Alembic commands ###
