"""audit_log 与 write_intent

Revision ID: dd8bbee17642
Revises:
Create Date: 2026-09-02 21:55:09.045638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dd8bbee17642"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("phase", sa.String(length=8), nullable=False, comment="attempt | outcome"),
        sa.Column(
            "occurred_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.String(length=32), nullable=False, comment="操作者，取自会话 context"
        ),
        sa.Column("action_type", sa.String(length=8), nullable=False, comment="read | write"),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False, comment="langgraph | dify | rpa"),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("target_table", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("before_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confirm_token_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=True,
            comment="success | failed | degraded | cancelled",
        ),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("model_tier", sa.String(length=8), nullable=True, comment="M0..M4"),
        sa.Column("ttft_ms", sa.Integer(), nullable=True, comment="首 token 延迟，流式才有"),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("retrieval_ms", sa.Integer(), nullable=True, comment="与 LLM 耗时分离以便归因"),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "request_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="已脱敏",
        ),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_ref", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_target", "audit_log", ["target_table", "target_id"], unique=False)
    op.create_index("ix_audit_log_trace_id", "audit_log", ["trace_id"], unique=False)
    op.create_index("ix_audit_log_user_time", "audit_log", ["user_id", "occurred_at"], unique=False)
    op.create_table(
        "write_intent",
        sa.Column("confirm_token", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "intent_type",
            sa.String(length=32),
            nullable=False,
            comment="create_order | update_order_status | ...",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="用户确认过的完整载荷",
        ),
        sa.Column(
            "state", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "result_ref",
            sa.String(length=64),
            nullable=True,
            comment="执行结果的业务主键，支撑重复提交返回原结果",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("consumed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending', 'confirmed', 'cancelled', 'expired')",
            name=op.f("ck_write_intent_state_enum"),
        ),
        sa.PrimaryKeyConstraint("confirm_token", name=op.f("pk_write_intent")),
    )
    op.create_index(
        "ix_write_intent_expires_pending",
        "write_intent",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_index(
        "ix_write_intent_session_state", "write_intent", ["session_id", "state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_write_intent_session_state", table_name="write_intent")
    op.drop_index(
        "ix_write_intent_expires_pending",
        table_name="write_intent",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_table("write_intent")
    op.drop_index("ix_audit_log_user_time", table_name="audit_log")
    op.drop_index("ix_audit_log_trace_id", table_name="audit_log")
    op.drop_index("ix_audit_log_target", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
