"""P2.4.2 业务表补 region —— 区域级权限的落点

Revision ID: eea304cd7f9c
Revises: 5b9c3e014e06
Create Date: 2026-09-10 20:33:49.968585
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eea304cd7f9c"
down_revision: str | None = "5b9c3e014e06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_batch",
        sa.Column("region", sa.String(length=16), nullable=False, comment="仓库所属区域"),
    )
    op.create_index(
        "ix_inventory_batch_scope", "inventory_batch", ["bu_code", "region"], unique=False
    )
    op.add_column(
        "production_line",
        sa.Column("region", sa.String(length=16), nullable=False, comment="产线所在区域"),
    )
    op.create_index(
        "ix_production_line_scope", "production_line", ["bu_code", "region"], unique=False
    )
    op.add_column(
        "sales_order",
        sa.Column("region", sa.String(length=16), nullable=False, comment="客户所属区域"),
    )
    op.create_index("ix_sales_order_scope", "sales_order", ["bu_code", "region"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sales_order_scope", table_name="sales_order")
    op.drop_column("sales_order", "region")
    op.drop_index("ix_production_line_scope", table_name="production_line")
    op.drop_column("production_line", "region")
    op.drop_index("ix_inventory_batch_scope", table_name="inventory_batch")
    op.drop_column("inventory_batch", "region")
    # ### end Alembic commands ###
